// templates/react/src/components/HelloWorld/index.tsx
interface IProps {
  msg: string;
}

const HelloWorld = (props: IProps) => {
  const [count, setCount] = useState(0);
  return (
    <>
      <h1>{props.msg}</h1>

      <button type="button" onClick={() => setCount(count + 1)}>
        count is {count}
      </button>

      <p>
        Check out
        <a
          href="https://www.npmjs.com/package/@atox/create-vite"
          target="_blank"
        >
          @atox/create-vite
        </a>
        , Vite template starter
      </p>
    </>
  );
};

export default HelloWorld;

// packages/create-vite/templates/vue/src/components/HelloWorld/index.vue
<template>
  <h1>{{ msg }}</h1>

  <button type="button" @click="count++">count is {{ count }}</button>

  <p>
    Check out
    <a href="https://www.npmjs.com/package/@atox/create-vite" target="_blank"
      >@atox/create-vite</a
    >, Vite template starter
  </p>
</template>
<script lang="ts" setup>
defineProps<{ msg: string }>();

const count = ref(0);
</script>
