// packages/create-vite/templates/vue/src/views/Home/index.vue
<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo">
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="@/assets/vue.svg" class="logo vue" alt="Vue logo">
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>
<style lang="less" scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/create-vite/templates/react/src/views/Home/index.tsx
import classNames from "classnames";
import styles from "./index.module.less";
import HelloWorld from "@/components/HelloWorld";
import ReactSvg from "@/assets/react.svg";

const Home = () => {
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img
            src="/vite.svg"
            className={classNames(styles["logo"])}
            alt="Vite logo"
          />
        </a>
        <a href="https://react.dev/" target="_blank">
          <img
            src={ReactSvg}
            className={classNames(styles["logo"], styles["react"])}
            alt="React logo"
          />
        </a>
      </div>
      <HelloWorld msg="Vite + React" />
    </>
  );
};

export default Home;
